apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-config
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  DATABASE_URL: "postgresql://<DB_USER>:<DB_PASSWORD>@{{ .Release.Name }}-postgresql:5432/ai-sw-ide"
  NAMESPACE: {{ .Release.Namespace | quote }}
  PROMETHEUS_ADDRESS: {{ .Values.global.environment.services.prometheus | quote }}
  NODE_NAMES: {{ .Values.global.environment.nodes.workers | quote }}
  CORS_ORIGINS: {{ .Values.global.environment.cors.origins | quote }}
  SECRET_ALGORITHM: {{ .Values.global.environment.app.secretAlgorithm | quote }}
  LOG_LEVEL: {{ .Values.global.environment.app.logLevel | quote }}
  GPU_FETCH: {{ .Values.global.environment.app.gpuFetchInterval | quote }}
  NFS_ADDRESS: {{ .Values.global.environment.nfs.address | quote }}
  REDIS_URL: {{ .Values.global.environment.services.redis | quote }}
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.global.environment.app.secretKey | b64enc }}
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
