apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "data-observer.fullname" . }}
  labels:
    {{- include "data-observer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "data-observer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "data-observer.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        {{- if .Values.nfs.enabled }}
        volumeMounts:
        - name: nfs-volume
          mountPath: {{ .Values.nfs.mountPath }}
          readOnly: {{ .Values.nfs.readOnly | default true }}
        {{- end }}
        env:
        {{- range .Values.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- if .Values.healthCheck.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.healthCheck.path }}
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: {{ .Values.healthCheck.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthCheck.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.healthCheck.path }}
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: {{ .Values.healthCheck.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthCheck.readinessProbe.periodSeconds }}
        {{- end }}
      {{- if .Values.nfs.enabled }}
      volumes:
      - name: nfs-volume
        nfs:
          server: {{ .Values.global.environment.nfs.address }}
          path: {{ .Values.nfs.path }}
          readOnly: {{ .Values.nfs.readOnly | default true }}
      {{- end }}
