replicaCount: 1

image:
  repository: <REGISTRY_ADDRESS>/ai-sw-ide/observer
  tag: "1.0"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

env:
  - name: NFS_ROOT
    value: "/nfsvolume"

# NFS Volume configuration (server from global.environment.nfs.address)
nfs:
  enabled: true
  path: "/nfsvolume"
  mountPath: "/nfsvolume"
  readOnly: true

# Health Check configuration
healthCheck:
  enabled: true
  path: "/health"
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 5

nodeSelector: {}
tolerations: []
affinity: {}
