replicaCount: 1

image:
  repository: <REGISTRY_ADDRESS>/ai-sw-ide/frontend
  tag: "1.0.1"
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30080

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

# Health Check configuration
healthCheck:
  enabled: true
  path: "/"
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 5

# ConfigMap data
config:
  apiUrl: "/api"
  backendServiceUrl: "http://ai-sw-ide-backend-service.ai-sw-ide.svc.cluster.local:8000"

# Additional environment variables
env: []

nodeSelector: {}
tolerations: []
affinity: {}
