replicaCount: 1

image:
  repository: <REGISTRY_ADDRESS>/ai-sw-ide/backend
  tag: "1.0"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

rbac:
  create: true

service:
  type: NodePort
  port: 8000
  targetPort: 8000
  nodePort: 30800

ingress:
  enabled: false

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Health Check configuration
healthCheck:
  enabled: true
  path: "/"
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 5

# ConfigMap data
config:
  PROMETHEUS_ADDRESS: "<YOUR_PROMETHEUS_ADDRESS>"
  NODE_NAMES: "<YOUR_WORKER_NODE_NAMES>(comma-separated: e.g. k8s-worker-1,k8s-worker-2)"
  DATA_OBSERVER_URL: "http://data-observer-service.ai-sw-ide.svc.cluster.local:8000"
  CORS_ORIGINS: "http://ai-sw-ide-frontend.ai-sw-ide.svc.cluster.local:4000,http://localhost:4000,http://127.0.0.1:4000"
  APP_PORT: "8000"
  SECRET_ALGORITHM: "HS256"
  LOG_LEVEL: "INFO"
  GPU_FETCH: "30"
  NFS_ADDRESS: "<YOUR_NFS_SERVER_IP>"

# Secret data (will be base64 encoded)
secrets:
  SECRET_KEY: "<YOUR_SECRET_KEY>"

nodeSelector: {}
tolerations: []
affinity: {}
