apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-sw-ide-frontend
  namespace: ai-sw-ide
  labels:
    app: ai-sw-ide-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-sw-ide-frontend
  template:
    metadata:
      labels:
        app: ai-sw-ide-frontend
    spec:
      containers:
      - name: frontend
        image: 172.40.10.198:30002/ai-sw-ide/frontend:1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: ai-sw-ide-frontend-config
              key: API_URL
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: nginx-config
        configMap:
          name: ai-sw-ide-frontend-config
          items:
          - key: nginx.conf
            path: nginx.conf 