apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
- configmap.yaml
- deployment.yaml
- service.yaml

commonLabels:
  component: ai-sw-ide-frontend
  part-of: ai-sw-ide 